apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-refw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-refw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-refw
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-refw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-refw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-luns-tenant/rhtap-demo-app/hacbs-test-project-refw@sha256:1ac60545f1311271bc78bdb434dd4db549a453abb35fc1adc60e76834b12e3b3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
